version: "3"
services:
  odoo:
    image: odoo:17  # Specify the Odoo image here
    restart: unless-stopped
    volumes:
      - odoo_lib:/var/lib/odoo
      - ./modules:/mnt/extra-addons
      - ./third-party-modules:/mnt/third-party-modules
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
    links:
      - db
    command: --log-handler :DEBUG
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 8061:5432
    volumes:
      - odoo17_postgres_data:/var/lib/postgresql/data # Rename postgres volumn with odoo version 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  odoo_lib:
  odoo17_postgres_data: # Use same db volumns
