version: "3"
services:
  odoo:
    ports:
      - 8069:8069
    environment:
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
    command: --log-handler :DEBUG
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
