name: Odoo CI/CD Checks

on:
  pull_request:
  push:
    branches:
      - main
      - "18.0"
      - "17.0"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Pre-commit
        run: |
          pip install pre-commit
      - name: Run Pre-commit Hooks
        run: |
          pre-commit run --all-files

  test:
    runs-on: ubuntu-24.04
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        odoo_version: ["17.0"]
        pg_version: ["15"]
        python_version: ["3.10"]
    env:
      DOCKER_BUILDKIT: 1
      PG_VERSIONS: ${{ matrix.pg_version }}
      ODOO_MINOR: ${{ matrix.odoo_version }}
      DOCKER_TAG: ${{ matrix.odoo_version }}
    services:
      postgres:
        image: postgres:${{ matrix.pg_version }}
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Create Docker Network
        run: |
          docker network create odoo-network
      - name: Wait for PostgreSQL to be ready
        run: |
          docker ps
          POSTGRES_CONTAINER=$(docker ps --filter "ancestor=postgres:${{ matrix.pg_version }}" --format "{{.Names}}")
          echo "PostgreSQL container name: $POSTGRES_CONTAINER"
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U odoo && break
            sleep 5
          done
      - name: Start Odoo in Docker
        run: |
          POSTGRES_CONTAINER=$(docker ps --filter "ancestor=postgres:${{ matrix.pg_version }}" --format "{{.Names}}")
          docker run -d --name odoo \
            --network odoo-network \
            -e HOST=$POSTGRES_CONTAINER \
            -e USER=odoo \
            -e PASSWORD=odoo \
            -e DATABASE=odoo \
            -p 8069:8069 \
            odoo:${{ matrix.odoo_version }}
      - name: Wait for Odoo to Start
        run: sleep 30
      - name: Run Tests
        run: |
          pytest --odoo-db-host=localhost --odoo-db-user=odoo --odoo-db-password=odoo --odoo-db-name=odoo

  build:
    runs-on: ubuntu-24.04
    needs: test
    strategy:
      matrix:
        odoo_version: ["17.0"]
        platforms: ["linux/amd64,linux/arm64"]
    steps:
      - name: Clean Docker System Before Build
        run: |
          docker system prune -af || true
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/${{ matrix.odoo_version }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            mydockerhub/odoo:${{ matrix.odoo_version }}

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying Odoo ${{ matrix.odoo_version }} to production server"
