name: Odoo CI/CD Checks

on:
  push:
    branches:
      - main
      - "18.0"
  pull_request:
    branches:
      - main
      - "18.0"

jobs:
  odoo-tests:
    name: Run Odoo Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Start Odoo Service
        run: |
          docker run -d --name odoo \
            --link postgres:db \
            -e HOST=db \
            -e USER=odoo \
            -e PASSWORD=odoo \
            -e DATABASE=odoo \
            -p 8069:8069 \
            odoo:17.0

      - name: Wait for Odoo to be ready
        run: |
          echo "Waiting for Odoo to start..."
          sleep 30

      - name: Set PYTHONPATH for Odoo
        run: |
          echo "PYTHONPATH=/usr/lib/python3/dist-packages" >> $GITHUB_ENV
          echo "PYTHONPATH=$(pwd)/odoo" >> $GITHUB_ENV

      - name: Run Pytest with Odoo
        run: |
          pytest --odoo-db-host=postgres --odoo-db-user=odoo --odoo-db-password=odoo --odoo-db-name=odoo
