name: Odoo CI/CD Checks

on:
  push:
    branches:
      - main
      - "18.0"
  pull_request:
    branches:
      - main
      - "18.0"

jobs:
  odoo-tests:
    name: Run Odoo Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432

      odoo:
        image: odoo:17.0
        env:
          HOST: postgres
          USER: odoo
          PASSWORD: odoo
          DATABASE: odoo
        ports:
          - 8069:8069
        options: >-
          --health-cmd "curl --fail http://localhost:8069 || exit 1"
          --health-interval 10s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-odoo

      - name: Wait for Odoo to be ready
        run: |
          echo "Waiting for Odoo to start..."
          sleep 60  # ✅ รอให้ Odoo และ Postgres ทำงาน

      - name: Set PYTHONPATH for Odoo
        run: |
          echo "PYTHONPATH=/usr/lib/python3/dist-packages" >> $GITHUB_ENV
          echo "PYTHONPATH=$(pwd)/odoo" >> $GITHUB_ENV

      - name: Run Pytest with Odoo
        run: |
          pytest --odoo-db-host=localhost --odoo-db-user=odoo --odoo-db-password=odoo --odoo-db-name=odoo
