name: Odoo OCA CI

on:
  push:
    branches:
      - main
      - "18.0"
  pull_request:
    branches:
      - main
      - "18.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pre-commit (Linting)
        run: |
          pre-commit run --all-files

      - name: Run OCA Quality Tools
        run: |
          pip install pylint-odoo
          pylint --load-plugins=pylint_odoo extra-addons/

      - name: Run Odoo Tests
        run: |
          odoo --test-enable --stop-after-init --database odoo_test
